const assert = require('node:assert/strict');
const vm = require('node:vm');
const { loadModules } = require('./support/frontend-runtime');

let rowValues = {};
const rendered = {
  /** Capture the actual HTML generated by renderKitLocationRows and expose its fields. */
  set innerHTML(markup) {
    this.html = markup;
    const cabinet = markup.match(/<select class="kit-loc-cabinet"[^>]*><option value="([^"]*)" selected>/);
    const position = markup.match(/class="kit-loc-pos"[^>]*value="([^"]*)"/);
    const note = markup.match(/class="kit-loc-note"[^>]*value="([^"]*)"/);
    assert.ok(cabinet && position && note, 'rendered metadata inputs must be present');
    rowValues = { cabinet: cabinet[1], position: position[1], note: note[1] };
  },
};

/** Return a DOM-like row whose values were parsed from the rendered markup. */
const row = {
  /** @param {string} selector Field selector used by getKitLocations. */
  querySelector(selector) {
    const key = {
      '[data-role="kit-loc-cabinet"]': 'cabinet',
      '[data-role="kit-loc-pos"]': 'position',
      '[data-role="kit-loc-note"]': 'note',
    }[selector];
    assert.ok(key, `unexpected location field selector: ${selector}`);
    return { value: rowValues[key] };
  },
};

/** Escape values for this isolated DOM harness; test inputs contain no markup. */
function escapeForTest(value) {
  return String(value);
}

/** Render one selected cabinet option in the minimal DOM harness. */
function cabinetOptionsForTest(selected) {
  return `<option value="${selected}" selected>${selected}</option>`;
}

/** Resolve the location row container expected by the production renderer. */
function getElementByIdForTest(id) {
  return id === 'kit-location-rows' ? rendered : null;
}

/** Return the fake row only after production rendering has populated its markup. */
function querySelectorAllForTest(selector) {
  return selector === '#kit-location-rows [data-role="kit-location-row"]' ? [row] : [];
}

const context = vm.createContext({
  console,
  appState: { globalCabinetList: [{ name: '編號A' }] },
  esc: escapeForTest,
  _cabinetOptions: cabinetOptionsForTest,
  document: {
    getElementById: getElementByIdForTest,
    querySelectorAll: querySelectorAllForTest,
  },
});

loadModules(context, 'features/kits/state.js', 'features/kits/kit-modal.js');

context.kitsState.kitLocationRows = [{ cabinet: '編號A', position: '1-1', note: '主存區' }];
context.renderKitLocationRows();
const result = JSON.parse(vm.runInContext('JSON.stringify(getKitLocations())', context));
assert.deepEqual(result, [{ cabinet: '編號A', position: '1-1', note: '主存區' }]);
assert.ok(!rendered.html.includes('kit-loc-qty'), 'rendered location rows must not contain a qty field');
console.log('kit location runtime contract passed');
